# Set timezone to +00:00 so that times in dates aren't transformed.
timezone: Africa/Abidjan

# Necessary for concerts set in the future to be displayed.
future: true

exclude:
  - README.md
  - concert-example.md
  - musician-example.md
  - Gemfile
  - Gemfile.lock

collections:
  concerts:
    output: true
    permalink: /:path
  musicians:
    output: true
    permalink: /:path
  main_pages:
    output: true
    permalink: /:path
  sub_pages:
    output: true
    permalink: /:path

defaults:
  -
    values:
      layout: page
  -
    scope:
      path: ""
      type: concerts
    values:
      layout: concert
  -
    scope:
      path: ""
      type: musicians
    values:
      layout: musician