# Note: this will need to change if permanent daylight time is implemented.
timezone: America/Los_Angeles

# Necessary for concerts set in the future to be displayed.
future: true

excludes:
  - README.md

collections:
  concerts:
    output: true
    permalink: /:path
  musicians:
    output: true
    permalink: /:path
  main_pages:
    output: true
    permalink: /:path
  sub_pages:
    output: true
    permalink: /:path

defaults:
  -
    values:
      layout: page
  -
    scope:
      path: ""
      type: concerts
    values:
      layout: concert
  -
    scope:
      path: ""
      type: musicians
    values:
      layout: musician