# A YAML timestamp just before the desired active concert.
# Note the value must include a time as just a date will cause type errors.
# This time isn't displayed anywhere on the site, it's just used to select the active concert.
# The active concert will appear as a banner in the header and on the home page.
# Inputting the date of the desired concert but leaving time at 00:00:00 works great.
concert_date: 2019-07-01 00:00:00

# A list of sponsors that appear in the header of every page.
# name: The name of the sponsor i.e. organization.
# logo: The file name of the logo. Logos for header sponsors are stored in assets/header-sponsors
# url: The website of the sponsor.
header_sponsors:
  -
    name: 4 Culture
    logo: 4culture.png
    url: https://www.4culture.org/
  -
    name: Tulalip Cares
    logo: tulalip-cares.png
    url: https://www.tulalipcares.org/
  -
    name: Snohomish County Arts Commission
    logo: snoco-arts.png
    url: https://www.snocoarts.org/
  -
    name: Hazel Miller Foundation
    logo: hazel-miller.png
    url: http://hazelmillerfoundation.org/
  -
    name: King County Employee Giving Program
    logo: egp.jpg
    url: https://www.kingcounty.gov/audience/employees/giving.aspx